<a href="https://colab.research.google.com/github/fatmakara/PythonVeriAnaliz/blob/main/Python4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center> Güney Marmara ve TRAI
# <center> Python Veri Analizi Eğitimi
# <center> Ödev 4

### Veriyi özetleme

1.  3. Ders sonunda hazırladığınız 2021 ve 2022 yıllarına ait BIST30 ve EUR/TRY kur değerlerini içeren bileşke tablodan sadece ayın son işgününe ait değerleri içeren bir pivot tablo üretiniz.

In [1]:
import yfinance as yf
import plotly.express as px 
import plotly.graph_objects as go
import pandas as pd
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

In [2]:
# Kur EUR 2021:
Kur = yf.download("EURTRY=X", start = "2021-01-01", end = "2023-01-01")
Kur = Kur[["Adj Close"]]
Kur.columns = ["EUR"]

# BIST30 2021:
B30 = yf.download("XU030.IS", start = "2021-01-01", end = "2023-01-01")
B30 = B30[["Adj Close"]]
B30.columns = ["BIST30"]

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [3]:
B30_EUR = B30.merge(Kur, left_index=True, right_index =True)
B30_EUR

                 BIST30        EUR
Date
2021-01-04  1652.900024   9.105680
2021-01-05  1640.400024   9.088820
2021-01-06  1657.699951   9.081770
2021-01-07  1678.199951   9.006140
2021-01-08  1694.400024   8.998500
...                 ...        ...
2022-12-23  5885.200195  19.791670
2022-12-27  5876.700195  19.815269
2022-12-28  5789.399902  19.805389
2022-12-29  5915.200195  19.867519
2022-12-30  5944.799805  19.937571

[490 rows x 2 columns]

In [4]:
B30_EUR["Yıl-Ay"] = B30_EUR.index.strftime("%Y-%m") #küçük y ile yazarsam 21 getirir
B30_EUR

                 BIST30        EUR   Yıl-Ay
Date
2021-01-04  1652.900024   9.105680  2021-01
2021-01-05  1640.400024   9.088820  2021-01
2021-01-06  1657.699951   9.081770  2021-01
2021-01-07  1678.199951   9.006140  2021-01
2021-01-08  1694.400024   8.998500  2021-01
...                 ...        ...      ...
2022-12-23  5885.200195  19.791670  2022-12
2022-12-27  5876.700195  19.815269  2022-12
2022-12-28  5789.399902  19.805389  2022-12
2022-12-29  5915.200195  19.867519  2022-12
2022-12-30  5944.799805  19.937571  2022-12

[490 rows x 3 columns]

In [5]:
B30_EUR.head(30)

                 BIST30      EUR   Yıl-Ay
Date
2021-01-04  1652.900024  9.10568  2021-01
2021-01-05  1640.400024  9.08882  2021-01
2021-01-06  1657.699951  9.08177  2021-01
2021-01-07  1678.199951  9.00614  2021-01
2021-01-08  1694.400024  8.99850  2021-01
2021-01-11  1679.000000  8.96309  2021-01
2021-01-12  1686.800049  9.09150  2021-01
2021-01-13  1697.599976  9.09140  2021-01
2021-01-14  1681.000000  9.00060  2021-01
2021-01-15  1653.800049  8.94864  2021-01
2021-01-18  1682.699951  8.98705  2021-01
2021-01-19  1690.099976  9.02792  2021-01
2021-01-20  1691.199951  9.06183  2021-01
2021-01-21  1665.599976  8.98146  2021-01
2021-01-25  1637.099976  9.02598  2021-01
2021-01-26  1636.900024  8.99402  2021-01
2021-01-27  1575.199951  8.93513  2021-01
2021-01-28  1601.900024  8.95525  2021-01
2021-01-29  1572.400024  8.90257  2021-01
2021-02-01  1584.500000  8.82499  2021-02
2021-02-02  1602.800049  8.67803  2021-02
2021-02-03  1628.900024  8.65878  2021-02
2021-02-04  1627.699951  8.61142  2021-02
2021-02-05  1616.900024  8.53721  2021-02
2021-02-08  1625.300049  8.50010  2021-02
2021-02-09  1643.099976  8.53020  2021-02
2021-02-10  1646.400024  8.55900  2021-02
2021-02-11  1640.300049  8.54399  2021-02
2021-02-12  1628.400024  8.52594  2021-02
2021-02-16  1622.300049  8.44197  2021-02

In [6]:
pivot = B30_EUR.pivot_table(values =["BIST30", "EUR"], index= "Yıl-Ay", aggfunc="last")
pivot

              BIST30        EUR
Yıl-Ay
2021-01  1572.400024   8.902570
2021-02  1556.000000   8.904670
2021-03  1430.699951   9.748300
2021-04  1456.900024   9.923590
2021-05  1506.900024  10.347560
2021-06  1462.900024  10.384030
2021-07  1500.800049  10.050560
2021-08  1588.300049   9.869130
2021-09  1505.199951  10.343790
2021-10  1635.699951  11.003230
2021-11  1942.800049  14.347000
2021-12  2025.000000  14.993060
2022-01  2202.600098  15.034780
2022-02  2186.300049  15.688630
2022-03  2477.199951  16.353970
2022-04  2704.399902  15.531140
2022-05  2837.600098  17.646820
2022-06  2609.199951  17.240959
2022-07  2760.500000  18.285971
2022-08  3454.399902  18.194550
2022-09  3457.600098  18.145809
2022-10  4330.500000  18.480520
2022-11  5364.399902  19.230379
2022-12  5944.799805  19.937571

2. Ay kırılımlı olarak ürettiğiniz tabloyu grafik olarak inceleyiniz.

In [8]:
pivot["degisim"] = pivot["BIST30"].diff(1)
pivot["d_yon"] = pivot["degisim"].map(lambda x: "düşen gün"  if x < 0 else "yükselen gün")
pivot["degisim%"] = (pivot["degisim"]/pivot["BIST30"].shift(1)) 
pivot

              BIST30        EUR      degisim         d_yon  degisim%
Yıl-Ay
2021-01  1572.400024   8.902570          NaN  yükselen gün       NaN
2021-02  1556.000000   8.904670   -16.400024     düşen gün -0.010430
2021-03  1430.699951   9.748300  -125.300049     düşen gün -0.080527
2021-04  1456.900024   9.923590    26.200073  yükselen gün  0.018313
2021-05  1506.900024  10.347560    50.000000  yükselen gün  0.034319
2021-06  1462.900024  10.384030   -44.000000     düşen gün -0.029199
2021-07  1500.800049  10.050560    37.900024  yükselen gün  0.025907
2021-08  1588.300049   9.869130    87.500000  yükselen gün  0.058302
2021-09  1505.199951  10.343790   -83.100098     düşen gün -0.052320
2021-10  1635.699951  11.003230   130.500000  yükselen gün  0.086699
2021-11  1942.800049  14.347000   307.100098  yükselen gün  0.187748
2021-12  2025.000000  14.993060    82.199951  yükselen gün  0.042310
2022-01  2202.600098  15.034780   177.600098  yükselen gün  0.087704
2022-02  2186.300049  15.688630   -16.300049     düşen gün -0.007400
2022-03  2477.199951  16.353970   290.899902  yükselen gün  0.133056
2022-04  2704.399902  15.531140   227.199951  yükselen gün  0.091716
2022-05  2837.600098  17.646820   133.200195  yükselen gün  0.049253
2022-06  2609.199951  17.240959  -228.400146     düşen gün -0.080491
2022-07  2760.500000  18.285971   151.300049  yükselen gün  0.057987
2022-08  3454.399902  18.194550   693.899902  yükselen gün  0.251367
2022-09  3457.600098  18.145809     3.200195  yükselen gün  0.000926
2022-10  4330.500000  18.480520   872.899902  yükselen gün  0.252458
2022-11  5364.399902  19.230379  1033.899902  yükselen gün  0.238748
2022-12  5944.799805  19.937571   580.399902  yükselen gün  0.108195

In [9]:
px.bar(pivot,y = "degisim%",
       color = "d_yon", color_discrete_map={"yükselen gün":"green","düşen gün":"red"},
       title="BIST30 (1 Ocak 2021 =1)",
       hover_data = {'degisim%' : ':.2f'},
       labels = {'Date' : 'Tarih' },
       text_auto = '.0%')

3. Ders sonunda hazırladığınız 2021 ve 2022 yıllarına ait BIST30 ve EUR/USD kur değerlerini içeren bileşke tablodan sadece ayın son işgününe ait değerleri içeren bir tabloyu bir de resample yöntemi ile üretiniz.

In [10]:
Resample= B30_EUR.resample ("BM", convention = 'end').asfreq() #nan çıktı!!!
Resample

                 BIST30        EUR   Yıl-Ay
Date
2021-01-29  1572.400024   8.902570  2021-01
2021-02-26  1556.000000   8.904670  2021-02
2021-03-31  1430.699951   9.748300  2021-03
2021-04-30  1456.900024   9.923590  2021-04
2021-05-31          NaN        NaN      NaN
2021-06-30  1462.900024  10.384030  2021-06
2021-07-30  1500.800049  10.050560  2021-07
2021-08-31  1588.300049   9.869130  2021-08
2021-09-30  1505.199951  10.343790  2021-09
2021-10-29          NaN        NaN      NaN
2021-11-30  1942.800049  14.347000  2021-11
2021-12-31  2025.000000  14.993060  2021-12
2022-01-31  2202.600098  15.034780  2022-01
2022-02-28  2186.300049  15.688630  2022-02
2022-03-31  2477.199951  16.353970  2022-03
2022-04-29  2704.399902  15.531140  2022-04
2022-05-31  2837.600098  17.646820  2022-05
2022-06-30  2609.199951  17.240959  2022-06
2022-07-29  2760.500000  18.285971  2022-07
2022-08-31  3454.399902  18.194550  2022-08
2022-09-30  3457.600098  18.145809  2022-09
2022-10-31  4330.500000  18.480520  2022-10
2022-11-30  5364.399902  19.230379  2022-11
2022-12-30  5944.799805  19.937571  2022-12

In [11]:
Daily=B30_EUR.resample("d", convention="end").asfreq() #her günü türetelim
Daily.head(10)

                 BIST30      EUR   Yıl-Ay
Date
2021-01-04  1652.900024  9.10568  2021-01
2021-01-05  1640.400024  9.08882  2021-01
2021-01-06  1657.699951  9.08177  2021-01
2021-01-07  1678.199951  9.00614  2021-01
2021-01-08  1694.400024  8.99850  2021-01
2021-01-09          NaN      NaN      NaN
2021-01-10          NaN      NaN      NaN
2021-01-11  1679.000000  8.96309  2021-01
2021-01-12  1686.800049  9.09150  2021-01
2021-01-13  1697.599976  9.09140  2021-01

In [12]:
Filled =B30_EUR.resample("d", convention="end").asfreq().ffill() #nan günleri bir üst değerden kopyalayalım
Filled.head(10)

                 BIST30      EUR   Yıl-Ay
Date
2021-01-04  1652.900024  9.10568  2021-01
2021-01-05  1640.400024  9.08882  2021-01
2021-01-06  1657.699951  9.08177  2021-01
2021-01-07  1678.199951  9.00614  2021-01
2021-01-08  1694.400024  8.99850  2021-01
2021-01-09  1694.400024  8.99850  2021-01
2021-01-10  1694.400024  8.99850  2021-01
2021-01-11  1679.000000  8.96309  2021-01
2021-01-12  1686.800049  9.09150  2021-01
2021-01-13  1697.599976  9.09140  2021-01

In [13]:
Resample= Filled.resample ("BM", convention = 'end').asfreq() #tarihler artık yanıltıcı
Resample=Resample.set_index(['Yıl-Ay'])
Resample

              BIST30        EUR
Yıl-Ay
2021-01  1572.400024   8.902570
2021-02  1556.000000   8.904670
2021-03  1430.699951   9.748300
2021-04  1456.900024   9.923590
2021-05  1506.900024  10.347560
2021-06  1462.900024  10.384030
2021-07  1500.800049  10.050560
2021-08  1588.300049   9.869130
2021-09  1505.199951  10.343790
2021-10  1635.699951  11.003230
2021-11  1942.800049  14.347000
2021-12  2025.000000  14.993060
2022-01  2202.600098  15.034780
2022-02  2186.300049  15.688630
2022-03  2477.199951  16.353970
2022-04  2704.399902  15.531140
2022-05  2837.600098  17.646820
2022-06  2609.199951  17.240959
2022-07  2760.500000  18.285971
2022-08  3454.399902  18.194550
2022-09  3457.600098  18.145809
2022-10  4330.500000  18.480520
2022-11  5364.399902  19.230379
2022-12  5944.799805  19.937571

4. Resample yöntemi ile ürettiğiniz tabloyu grafik olarak inceleyiniz. 2. adımda elde ettiğiniz grafik ile karşılaştırarak yorumlayınız.

In [14]:
Resample["degisim"] = Resample["BIST30"].diff(1)
Resample["d_yon"] = Resample["degisim"].map(lambda x: "düşen gün"  if x < 0 else "yükselen gün")
Resample["degisim%"] = (Resample["degisim"]/Resample["BIST30"].shift(1)) 
Resample

              BIST30        EUR      degisim         d_yon  degisim%
Yıl-Ay
2021-01  1572.400024   8.902570          NaN  yükselen gün       NaN
2021-02  1556.000000   8.904670   -16.400024     düşen gün -0.010430
2021-03  1430.699951   9.748300  -125.300049     düşen gün -0.080527
2021-04  1456.900024   9.923590    26.200073  yükselen gün  0.018313
2021-05  1506.900024  10.347560    50.000000  yükselen gün  0.034319
2021-06  1462.900024  10.384030   -44.000000     düşen gün -0.029199
2021-07  1500.800049  10.050560    37.900024  yükselen gün  0.025907
2021-08  1588.300049   9.869130    87.500000  yükselen gün  0.058302
2021-09  1505.199951  10.343790   -83.100098     düşen gün -0.052320
2021-10  1635.699951  11.003230   130.500000  yükselen gün  0.086699
2021-11  1942.800049  14.347000   307.100098  yükselen gün  0.187748
2021-12  2025.000000  14.993060    82.199951  yükselen gün  0.042310
2022-01  2202.600098  15.034780   177.600098  yükselen gün  0.087704
2022-02  2186.300049  15.688630   -16.300049     düşen gün -0.007400
2022-03  2477.199951  16.353970   290.899902  yükselen gün  0.133056
2022-04  2704.399902  15.531140   227.199951  yükselen gün  0.091716
2022-05  2837.600098  17.646820   133.200195  yükselen gün  0.049253
2022-06  2609.199951  17.240959  -228.400146     düşen gün -0.080491
2022-07  2760.500000  18.285971   151.300049  yükselen gün  0.057987
2022-08  3454.399902  18.194550   693.899902  yükselen gün  0.251367
2022-09  3457.600098  18.145809     3.200195  yükselen gün  0.000926
2022-10  4330.500000  18.480520   872.899902  yükselen gün  0.252458
2022-11  5364.399902  19.230379  1033.899902  yükselen gün  0.238748
2022-12  5944.799805  19.937571   580.399902  yükselen gün  0.108195

In [15]:
px.bar(Resample,y = "degisim%",
       color = "d_yon", color_discrete_map={"yükselen gün":"green","düşen gün":"red"},
       title="BIST30 (1 Ocak 2021 =1)",
       hover_data = {'degisim%' : ':.2f'},
       labels = {'Date' : 'Tarih' },
       text_auto = '.0%')